/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab_8;
import javax.swing.*;
import java.awt.*;
import java.util.List;
import lab_8.JsonDatabaseManager;
import lab_8.Lesson;
import org.jfree.chart.*;
import org.jfree.chart.plot.*;
import org.jfree.data.category.DefaultCategoryDataset;
/**
 *
 * @author sarahkhaled
 */
public class ChartFrame extends JFrame {

    /**
     * Creates new form ChartFrame
     */
     public ChartFrame(String courseId) {
        setTitle("Course Analytics: " + courseId);
        setSize(1000, 600);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        JPanel panel = new JPanel(new GridLayout(1, 3));

        panel.add(createStudentPerformanceChart(courseId));
        panel.add(createQuizAveragesChart(courseId));
        panel.add(createCompletionChart(courseId));

        setContentPane(panel);
    }
     private ChartPanel createStudentPerformanceChart(String courseId) {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        List<Lesson> lessons = JsonDatabaseManager.getLessons(courseId);
        for (Lesson l : lessons) {
            dataset.addValue(l.getAverageScore(), "Average Score", l.getTitle());
        }
        JFreeChart chart = ChartFactory.createLineChart(
                "Student Performance", "Lesson", "Score",
                dataset, PlotOrientation.VERTICAL, false, true, false);
        return new ChartPanel(chart);
    }

    private ChartPanel createQuizAveragesChart(String courseId) {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        List<Lesson> lessons = JsonDatabaseManager.getLessons(courseId);
        for (Lesson l : lessons) {
            double avg = l.getQuiz() != null ? l.getAverageScore() : 0;
            dataset.addValue(avg, "Quiz Average", l.getTitle());
        }
        JFreeChart chart = ChartFactory.createBarChart(
                "Quiz Averages", "Lesson", "Score",
                dataset, PlotOrientation.VERTICAL, false, true, false);
        return new ChartPanel(chart);
    }

    private ChartPanel createCompletionChart(String courseId) {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        List<Lesson> lessons = JsonDatabaseManager.getLessons(courseId);
        for (Lesson l : lessons) {
            dataset.addValue(l.getCompletionPercentage(), "Completion %", l.getTitle());
        }
        JFreeChart chart = ChartFactory.createBarChart(
                "Completion %", "Lesson", "Completion %", dataset,
                PlotOrientation.VERTICAL, false, true, false);
        return new ChartPanel(chart);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
