/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab_8;

import java.awt.GridLayout;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sarahkhaled
 */
public class InsightsWindow extends javax.swing.JFrame {

    /**
     * Creates new form InsightsWindow
     */
   private String courseId;
public InsightsWindow(String courseId) {
        this.courseId = courseId;

        setTitle("Instructor Insights - " + courseId);
        setSize(400, 300);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        // Buttons
        JButton studentPerfBtn = new JButton("Student Performance (All Students)");
        JButton singleStudentBtn = new JButton("Single Student Performance");
        JButton quizAvgBtn = new JButton("Quiz Averages per Lesson");
        JButton completionBtn = new JButton("Lesson Completion %");

        // Action listeners
        studentPerfBtn.addActionListener(e -> ChartUtils.showStudentPerformanceChart(courseId));

        singleStudentBtn.addActionListener(e -> {
            List<String> students = CourseManagement.getEnrolledStudents(courseId);
            if (students.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No students enrolled in this course.");
                return;
            }

            String[] studentArray = students.toArray(new String[0]);
            String selectedStudent = (String) JOptionPane.showInputDialog(
                    this,
                    "Select a student to view performance:",
                    "Select Student",
                    JOptionPane.PLAIN_MESSAGE,
                    null,
                    studentArray,
                    studentArray[0]
            );

            if (selectedStudent != null) {
                ChartUtils.showStudentLineChart(courseId, selectedStudent);
            }
        });

        quizAvgBtn.addActionListener(e -> ChartUtils.showQuizAveragesChart(courseId));
        completionBtn.addActionListener(e -> ChartUtils.showLessonCompletionChart(courseId));

        // Panel layout
        JPanel panel = new JPanel(new GridLayout(4, 1, 10, 10));
        panel.add(studentPerfBtn);
        panel.add(singleStudentBtn);
        panel.add(quizAvgBtn);
        panel.add(completionBtn);

        add(panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsightsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsightsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsightsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsightsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
