/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab_8;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CYBER-TECH
 */
public class lessonsframe extends javax.swing.JFrame {
 private String courseId = "COURSE_ID_HERE"; // replace with actual courseId
    private DefaultTableModel lessonTableModel;
    /**
     * Creates new form lessonsframe
     */
   public lessonsframe() {
    this.courseId = "DEFAULT"; // or null
    initComponents();
}
    public lessonsframe(String courseId) {
    this.courseId = courseId; // save the selected course
    initComponents();
    lessonTableModel = (DefaultTableModel) jTable1.getModel();

    loadTable();

    jTable1.getSelectionModel().addListSelectionListener(e -> showContent());

   
}

    
    private void showContent() {
    int row = jTable1.getSelectedRow();
    if (row == -1) return;

    String lessonId = jTable1.getValueAt(row, 0).toString();
    List<Lesson> lessons = JsonDatabaseManager.getLessons(courseId);

    for (Lesson l : lessons) {
        if (l.getLessonId().equals(lessonId)) {
            JOptionPane.showMessageDialog(this, l.getContent(), l.getTitle(), JOptionPane.INFORMATION_MESSAGE);
            break;
        }
    }
}
    private void loadTable() {
        List<Lesson> lessons = JsonDatabaseManager.getLessons(courseId);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        for (Lesson L : lessons) {
            model.addRow(new Object[]{
                    L.getLessonId(),
                    L.getTitle(),
                    L.isCompleted() ? "Yes" : "No"
            });
        }
    }

 

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        addLesson = new javax.swing.JButton();
        deleteLesson = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Lesson ID", "Lesson Title", "Content"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        addLesson.setText("addLesson");
        addLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLessonActionPerformed(evt);
            }
        });

        deleteLesson.setText("deleteLesson");
        deleteLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteLessonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addLesson)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteLesson)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addLesson)
                    .addComponent(deleteLesson))
                .addGap(0, 63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addLessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLessonActionPerformed
       
        
        String lessonId = JOptionPane.showInputDialog(this, "Enter Lesson ID:");
    if (lessonId == null || lessonId.isEmpty()) return;
    List<Lesson> lessons = JsonDatabaseManager.getLessons(courseId);
    for (Lesson l : lessons) {
        if (l.getLessonId().equalsIgnoreCase(lessonId)) {
            JOptionPane.showMessageDialog(this,
                    "Lesson ID already exists! Please choose a different ID.",
                    "Duplicate ID",
                    JOptionPane.ERROR_MESSAGE);
            return; // stop adding
        }
    }

   String title = JOptionPane.showInputDialog(this, "Enter Lesson Title:");
    if (title == null || title.isEmpty()) return;

    String content = JOptionPane.showInputDialog(this, "Enter Lesson Content:");
    if (content == null) return;

    Lesson newLesson = new Lesson(lessonId, title, content, null); 
    lessons.add(newLesson);
    JsonDatabaseManager.saveLessons(courseId, lessons);

    loadTable();
    JOptionPane.showMessageDialog(this, "Lesson added successfully!");
    }//GEN-LAST:event_addLessonActionPerformed

    private void deleteLessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteLessonActionPerformed
         int row = jTable1.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Select a lesson first!");
        return;
    }

    String lessonId = jTable1.getValueAt(row, 0).toString();
    int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to delete lesson " + lessonId + "?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION);
    if (confirm != JOptionPane.YES_OPTION) return;

    List<Lesson> lessons = JsonDatabaseManager.getLessons(courseId);
    lessons.removeIf(l -> l.getLessonId().equals(lessonId));
    JsonDatabaseManager.saveLessons(courseId, lessons);

    loadTable();
   
    JOptionPane.showMessageDialog(this, "Lesson deleted successfully!");
    }//GEN-LAST:event_deleteLessonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lessonsframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lessonsframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lessonsframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lessonsframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lessonsframe().setVisible(true);
            }
        });
    }

    private void addLesson() {
        String lessonId = JOptionPane.showInputDialog(this, "Enter Lesson ID:");
        if (lessonId == null || lessonId.isEmpty()) return;
        

        String title = JOptionPane.showInputDialog(this, "Enter Lesson Title:");
        if (title == null || title.isEmpty()) return;

        String content = JOptionPane.showInputDialog(this, "Enter Lesson Content:");
        if (content == null) return;

        Lesson newLesson = new Lesson(lessonId, title, content, null);
        List<Lesson> lessons = JsonDatabaseManager.getLessons(courseId);
        lessons.add(newLesson);
        JsonDatabaseManager.saveLessons(courseId, lessons);

        loadTable();
        JOptionPane.showMessageDialog(this, "Lesson added successfully!");
    }

    private void deleteLesson() {
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select a lesson first!");
            return;
        }

        String lessonId = jTable1.getValueAt(row, 0).toString();
        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete lesson " + lessonId + "?",
                "Confirm Delete",
                JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) return;

        List<Lesson> lessons = JsonDatabaseManager.getLessons(courseId);
        lessons.removeIf(l -> l.getLessonId().equals(lessonId));
        JsonDatabaseManager.saveLessons(courseId, lessons);

        loadTable();
       
        JOptionPane.showMessageDialog(this, "Lesson deleted successfully!");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addLesson;
    private javax.swing.JButton deleteLesson;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
