/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab_8;

import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author Linae
 */
public class StudentEnrolled extends javax.swing.JFrame {

    /**
     * Creates new form studentDashboard
     */
    private String studentId; // logged-in student id
    private DefaultTableModel lessonTableModel;

    public StudentEnrolled(String studentId) {
        this.studentId = studentId;
        initComponents();
        loadEnrolledCourses();
    }

    private StudentEnrolled() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        coursesList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        logoutBtn = new javax.swing.JButton();
        back = new javax.swing.JButton();
        quizBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        coursesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(coursesList);

        jLabel1.setText("Courses");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Lesson ID", "Title", "Complete"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        back.setText("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        quizBtn.setText("Start Quiz");
        quizBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quizBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(back)
                        .addGap(43, 43, 43)
                        .addComponent(quizBtn)
                        .addGap(36, 36, 36)
                        .addComponent(logoutBtn)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutBtn)
                    .addComponent(back)
                    .addComponent(quizBtn))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
      private void loadEnrolledCourses() {
    StudentService ss = new StudentService();

    List<String> enrolledIds = ss.getEnrolledCourseIds(studentId);

    DefaultListModel<String> listModel = new DefaultListModel<>();

    
    JSONArray allCourses = CourseManagement.browseCourses();

   
    for (int i = 0; i < allCourses.length(); i++) {
        JSONObject c = allCourses.getJSONObject(i);
        String courseId = c.getString("courseId");

        if (enrolledIds.contains(courseId)) {
            listModel.addElement(courseId + " - " + c.getString("title"));
        }
    }

    coursesList.setModel(listModel);

  
    coursesList.addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting()) {
            loadLessons();
        }
    });
}

 private void loadLessons() {
    lessonTableModel = (DefaultTableModel) jTable1.getModel();

    lessonTableModel.setRowCount(0);
    String selected = coursesList.getSelectedValue();
    if (selected == null) return;

    String courseId = selected.split(" - ")[0];
    JSONArray lessons = CourseManagement.viewLessons(courseId);
    StudentService ss = new StudentService();

    for (int i = 0; i < lessons.length(); i++) {
        JSONObject l = lessons.getJSONObject(i);
        String lessonId = l.getString("lessonId");
        String title = l.getString("title");

        LessonProgress lp = ss.getLessonProgress(studentId, courseId, lessonId);
        boolean completed = lp != null && lp.isPassed();
        int score = lp != null ? lp.getScore() : 0;

        lessonTableModel.addRow(new Object[]{lessonId, title, completed, score});
    }
}

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        this.dispose(); // close dashboard
        new LoginFrame().setVisible(true); // show login
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.dispose();

    // Open the StudentDashboard and pass the student ID
    studentDashboard dashboard = new studentDashboard(studentId);
    dashboard.setVisible(true);

    // Close the current StudentEnrolled frame
    this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void quizBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quizBtnActionPerformed
        // TODO add your handling code here:
        // Get selected course
    String selectedCourse = coursesList.getSelectedValue();
    if (selectedCourse == null) {
        JOptionPane.showMessageDialog(this, "Please select a course first.");
        return;
    }
    String courseId = selectedCourse.split(" - ")[0];

    // Get selected lesson from table
    int selectedRow = jTable1.getSelectedRow();
    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(this, "Please select a lesson first.");
        return;
    }
    String lessonId = (String) lessonTableModel.getValueAt(selectedRow, 0);
    boolean completed = (boolean) lessonTableModel.getValueAt(selectedRow, 2);

    if (completed) {
        JOptionPane.showMessageDialog(this, "You have already completed this lesson.");
        return;
    }

    // Get Student object
    StudentService ss = new StudentService();
    Student student = ss.getStudentById(studentId); // Make sure this method exists

    // Get Lesson object
    Lesson lesson = CourseManagement.getLesson(courseId, lessonId); // Make sure this method exists

    if (student == null || lesson == null) {
        JOptionPane.showMessageDialog(this, "Error: unable to load student or lesson data.");
        return;
    }

    // Open QuizFrame using existing constructor
    QuizFrame quizFrame = new QuizFrame(student, lesson, ss, courseId);
    quizFrame.setVisible(true);

    }//GEN-LAST:event_quizBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            // Replace "STUDENT_ID" with a real test ID
            new StudentEnrolled("STUDENT_ID").setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JList<String> coursesList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton quizBtn;
    // End of variables declaration//GEN-END:variables
}
